// Auto-generated by scripts/generate-logo-manifest.mjs. Do not edit manually.
export const logoFilenames = [
  "claude.png",
  "Deepseek-Logo-White-PNG(1).png",
  "HF.png",
  "L.png",
  "n8n_full_black_logo.png",
  "OpenAI-Logo-PNG(1).png",
  "pinecone-seeklogo.png",
  "pngfind.com-aws-logo-png-731296.png",
  "qdrant-seeklogo.png",
  "qwen-ai-logo.png",
  "supabase-logo.png"
] as const;

export const logoUrls = logoFilenames.map((name) => `/files/logo/${name}`);
